### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by 7flash** [guatedude2/node-readfiles#11]
```
.pnpm/node-readfiles@0.3.1/node_modules/node-readfiles/lib/readfiles.js:15
define("src/build-filter", ["require", "exports"], function (require, exports) {
^

ReferenceError: define is not defined
    at Object.<anonymous> (/home/berliangur/ten25-second/ten25-third/node_modules/.pnpm/node-readfiles@0.3.1/node_modules/node-readfiles/lib/readfiles.js:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/berliangur/ten25-second/ten25-third/first.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
```

**Comment by guatedude2** [comment]
What version of node are you running?

**Comment by 7flash** [comment]
v16

**Comment by guatedude2** [comment]
This is my bad. It should be compiling in common js not AMD. I'll update it

**Comment by ChrisCarini** [comment]
Hello from the end of 2025! Was this ever updated at all? I just ran into the same issue, and me fact-checking AI's response lead me to this issue.

**Comment by guatedude2** [comment]
I haven't touched this project in a while. I'll take a look

**Comment by guatedude2** [comment]
@ChrisCarini could you try with the latest version 0.4.0

**Comment by ChrisCarini** [comment]
Hey @guatedude2 - first off, thanks for taking a look!

I just tried having Copilot upgrading my GHA that was running into the issue that lead me here, and it took 2 interesting approaches (the second one was because I told it to *not* do the first one, since it felt weird):

1. Patch this library with `patch-package` to work around the fact this is compiled in AMD (Copilot said `The 0.4.0 version is compiled as AMD modules ("module": "amd" in tsconfig), which is not compatible with Node.js's CommonJS require(). This is actually a bug in the published package - the compiled output uses define() which is an AMD construct not available in Node.js.`)
2. Replace this library with Node.js built-in `fs.readdir` (again, identifying that there was issues with this package because of AMD)

_(also, it's worth noting, I am certainly no TS/JS expert, so a bit of this is over my head. The past month or so, I've been taking the 'lazy developer' route and just feeding things in my TS/JS-based GHAs to Copilot to fix, and it's worked decently so far..)_

After letting Copilot do it's thing twice, I'm coming back here seeing your message from 2022:

> It should be compiling in common js not AMD. I'll update it

It looks like this is still compiling in AMD in `tsconfig.json` - are you still open to updating that (and releasing another version, sorry 😅) so I can give that a try?


**Edit:** Oh, also, if it's helpful, here is the draft PR with the commits that Copilot made to try and fix the issue. If it's helpful, I can also try to share the Copilot Agent session with you, so you can go through the steps it took and how it tried to rationalize things here. Just let me know!
